name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - uses: sonarsource/sonarqube-scan-action@v1
        with:
          args: -X
        env:
          SONAR_TOKEN: sqp_3213ce1c8cc2d9c1e48345c5c8cd0c005e5d79fb
          SONAR_HOST_URL: https://50ff-171-79-127-166.ngrok-free.app
